---
- hosts: my_k8s_cluster
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: pre_k8s_install }
    - { role: docker_runtime }
    - { role: install_kubeadm }

- hosts: master_node
  any_errors_fatal: true
  become: true
  become_method: sudo
  run_once: true
  collections:
    - community.kubernetes
  environment:
    KUBECONFIG: /home/{{ ansible_env.SUDO_USER }}/.kube/config
  roles:
    - { role: init_cfg_master }
    - { role: install_k8s_calico }
    - { role: k8s_token_cert }
    - { role: k8s_dashboard }
  tasks:
    - name: Copy from remote(master ndoe - /etc/kubernetes/admin.conf) to local (/tmp/admin.conf)
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/
        force: yes
        flat: true

#- hosts: 127.0.0.1
#  connection: local
#  tasks: 
#    - name: open 

- hosts: worker_nodes
  any_errors_fatal: true
  become: true
  become_method: sudo
  collections:
    - community.kubernetes
  tasks:
    - name: Fecth from local (/tmp/admin.conf) to remote (worker node - $HOME/.kube/config)
      copy:
        src: /tmp/admin.conf
        dest: /home/{{ ansible_env.SUDO_USER }}/.kube/config
        force: yes
  roles:
   - { role: join_worker }